CREATE TABLE dbo.Users (
  Id NVARCHAR(128) NOT NULL CONSTRAINT PK_Users PRIMARY KEY,
  Email NVARCHAR(320) NOT NULL,
  DisplayName NVARCHAR(200) NULL,
  EmployeeName NVARCHAR(200) NULL,
  EmployeeId NVARCHAR(100) NULL,
  Mobile NVARCHAR(50) NULL,
  Department NVARCHAR(150) NULL,
  IsAdmin BIT NOT NULL CONSTRAINT DF_Users_IsAdmin DEFAULT 0,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Users_UpdatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_Users_Email UNIQUE (Email)
);

CREATE TABLE dbo.Assets (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Assets PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  EmployeeId NVARCHAR(100) NULL, EmployeeName NVARCHAR(200) NULL, UserEmail NVARCHAR(320) NULL,
  MobileNumber NVARCHAR(50) NULL, Department NVARCHAR(150) NULL, Location NVARCHAR(200) NULL,
  OwnerId NVARCHAR(128) NULL, Category NVARCHAR(50) NOT NULL, SerialNumber NVARCHAR(150) NULL,
  Manufacturer NVARCHAR(150) NULL, Ownership NVARCHAR(30) NULL, VendorName NVARCHAR(200) NULL,
  Model NVARCHAR(150) NULL, PurchaseDate DATE NULL, PurchasePrice DECIMAL(18,2) NULL,
  WarrantyExpiration DATE NULL, Condition NVARCHAR(30) NULL, Status NVARCHAR(30) NULL,
  CpuManufacturer NVARCHAR(100) NULL, CpuModel NVARCHAR(100) NULL, CpuGeneration NVARCHAR(100) NULL,
  RamType NVARCHAR(50) NULL, RamSizeGb INT NULL, StorageType NVARCHAR(50) NULL,
  StorageCapacityGb INT NULL, Os NVARCHAR(100) NULL, OperatingSystemVersion NVARCHAR(100) NULL,
  MacAddress NVARCHAR(100) NULL, PurchaseOrderNumber NVARCHAR(100) NULL, Notes NVARCHAR(MAX) NULL,
  ImageUrl NVARCHAR(1000) NULL, TagsJson NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Assets_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Assets_UpdatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Assets_Owner FOREIGN KEY (OwnerId) REFERENCES dbo.Users(Id)
);

CREATE TABLE dbo.AssetRequests (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AssetRequests PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  RequesterId NVARCHAR(128) NOT NULL, RequesterEmail NVARCHAR(320) NOT NULL,
  RequesterName NVARCHAR(200) NULL, RequesterDepartment NVARCHAR(150) NULL,
  EmployeeId NVARCHAR(100) NULL, EmployeeName NVARCHAR(200) NULL, Mobile NVARCHAR(50) NULL,
  Category NVARCHAR(50) NOT NULL, Manufacturer NVARCHAR(150) NULL, Model NVARCHAR(150) NULL,
  Specifications NVARCHAR(MAX) NULL, Justification NVARCHAR(MAX) NULL,
  Priority NVARCHAR(30) NOT NULL, Status NVARCHAR(30) NOT NULL CONSTRAINT DF_AssetRequests_Status DEFAULT 'pending',
  AdminNotes NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_AssetRequests_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_AssetRequests_UpdatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_AssetRequests_Requester FOREIGN KEY (RequesterId) REFERENCES dbo.Users(Id)
);

CREATE TABLE dbo.AssetRequestComments (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AssetRequestComments PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  RequestId UNIQUEIDENTIFIER NOT NULL, AuthorId NVARCHAR(128) NOT NULL, AuthorName NVARCHAR(200) NULL,
  AuthorEmail NVARCHAR(320) NULL, AuthorRole NVARCHAR(30) NULL, Text NVARCHAR(MAX) NOT NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_AssetRequestComments_CreatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_AssetRequestComments_Request FOREIGN KEY (RequestId) REFERENCES dbo.AssetRequests(Id) ON DELETE CASCADE
);

CREATE TABLE dbo.Incidents (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Incidents PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  IncidentNumber INT NOT NULL CONSTRAINT UQ_Incidents_Number UNIQUE,
  ReporterId NVARCHAR(128) NOT NULL, ReporterEmail NVARCHAR(320) NOT NULL, ReporterName NVARCHAR(200) NULL,
  ReporterEmployeeId NVARCHAR(100) NULL, ReporterMobile NVARCHAR(50) NULL, ReporterDepartment NVARCHAR(150) NULL,
  Title NVARCHAR(300) NOT NULL, AssetId NVARCHAR(100) NULL, AssetName NVARCHAR(200) NULL,
  Description NVARCHAR(MAX) NULL, Severity NVARCHAR(30) NOT NULL, Category NVARCHAR(50) NOT NULL,
  Status NVARCHAR(40) NOT NULL CONSTRAINT DF_Incidents_Status DEFAULT 'open', AdminNotes NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Incidents_CreatedAt DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Incidents_UpdatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Incidents_Reporter FOREIGN KEY (ReporterId) REFERENCES dbo.Users(Id)
);

CREATE TABLE dbo.IncidentComments (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_IncidentComments PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  IncidentId UNIQUEIDENTIFIER NOT NULL, AuthorId NVARCHAR(128) NOT NULL, AuthorName NVARCHAR(200) NULL,
  AuthorEmail NVARCHAR(320) NULL, AuthorRole NVARCHAR(30) NULL, Text NVARCHAR(MAX) NOT NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_IncidentComments_CreatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_IncidentComments_Incident FOREIGN KEY (IncidentId) REFERENCES dbo.Incidents(Id) ON DELETE CASCADE
);

CREATE TABLE dbo.ActivityLogs (
  Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_ActivityLogs PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  Module NVARCHAR(40) NOT NULL, Action NVARCHAR(80) NOT NULL, Description NVARCHAR(MAX) NOT NULL,
  PerformedBy NVARCHAR(200) NOT NULL, PerformedByEmail NVARCHAR(320) NULL,
  TargetName NVARCHAR(300) NULL, TargetId NVARCHAR(100) NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_ActivityLogs_CreatedAt DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.NotificationTokens (
  Token NVARCHAR(500) NOT NULL CONSTRAINT PK_NotificationTokens PRIMARY KEY,
  UserId NVARCHAR(128) NOT NULL, Email NVARCHAR(320) NULL,
  CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_NotificationTokens_CreatedAt DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_NotificationTokens_User FOREIGN KEY (UserId) REFERENCES dbo.Users(Id) ON DELETE CASCADE
);
